/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as WinsRouteImport } from './routes/wins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaigns': typeof CampaignsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/scorecard': typeof ScorecardRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaigns': typeof CampaignsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/scorecard': typeof ScorecardRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaigns': typeof CampaignsRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/scorecard': typeof ScorecardRoute
  '/wins': typeof WinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/campaigns'
    | '/pricing'
    | '/resources'
    | '/scorecard'
    | '/wins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/campaigns'
    | '/pricing'
    | '/resources'
    | '/scorecard'
    | '/wins'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/campaigns'
    | '/pricing'
    | '/resources'
    | '/scorecard'
    | '/wins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CampaignsRoute: typeof CampaignsRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  ScorecardRoute: typeof ScorecardRoute
  WinsRoute: typeof WinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CampaignsRoute: CampaignsRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  ScorecardRoute: ScorecardRoute,
  WinsRoute: WinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
